### ISSUE TITLE
Arrow keys bubbling to browser

### ISSUE THREAD

**Issue by omarestrella** [jreel/Js-Roguelike-Tutorial#2]
When you are in the game and you hit the arrow keys, it scrolls the browser window. If you handle the event where you process input and `stopPropagation()`, it should stop.

https://github.com/jreel/Js-Roguelike-Tutorial/blob/4769ef4501e24cf7a7320987887d39d26e6701a6/js/screens.js#L187

**Comment by jreel** [comment]
Thanks for the bug report! Please test the demo again and let me know if the issue is still there.

http://jreel.github.io/Js-Roguelike-Tutorial/

**Comment by omarestrella** [comment]
Looks fixed on my end. No longer seeing the issue!

**Comment by jreel** [comment]
Great! Thanks for playtesting :)
